### ISSUE TITLE
No-touch timer component

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#111]
[comment-deleted]

**Comment by dhowe** [comment]
We need a component that checks the time since the the user last touched the screen. If it hits 10 seconds, then it should show a prompt, asking if they want to continue; if 3 more seconds elapse it should go back to the home page. 

This should be present on every page that requires input or a button press from the user

**Comment by aaronalbinson** [comment]
Countdown's not visible, happen in the background

**Comment by dhowe** [comment]
all dialogs should be consistently styled (see email error dialog ticket)

**Comment by kennyviperhk** [comment]
went through all pages and added a component IdleChecker in all interactive pages

**Comment by dhowe** [comment]
@kennyviperhk I don't see this working now -- does it need to be enabled?

**Comment by dhowe** [comment]
see #348

**Comment by dhowe** [comment]
Note that this is _disabled_ in development mode
