### ISSUE TITLE
InfluenceAFollower page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#259]
- [ ] change text from ‘Choose a participant’ to ‘Choose one:’ 

NOTE: this page template can be used with minor modifications for the 'Influence a Celebrity' page: see #233.

**Comment by billposters** [comment]
DESIGN SPEC: 

![Influence_A_Follower_design_spec](https://user-images.githubusercontent.com/48989022/58749805-7bd9d880-8482-11e9-956b-5b06f666a65d.jpg)

**Comment by billposters** [comment]
Design File: 

[Influence_A_Follower_design_spec.pdf](https://github.com/dhowe/spectre/files/3243852/Influence_A_Follower_design_spec.pdf)

**Comment by billposters** [comment]
Follower profile pic icon (150px diam): 

[Follower_profile_pic_circle.pdf](https://github.com/dhowe/spectre/files/3243853/Follower_profile_pic_circle.pdf)

**Comment by billposters** [comment]
Hi @aaronalbinson - can you let me know if this design spec gives you all the info you need to build it? 
I wasn't sure if you would need the exact measurements for the circle of profile pics. Each on is 150px diam and there is an asset for them in the comment above.

**Comment by pauljervis** [comment]
@billposters it would be really helpful to get the spacings from the bottom of one element to the top of the next rather than the bottom of the text to the bottom of the next text. Do you have this available? I also notice that the 185pix between the text and the top circles is from the base-line not from the bottom of the text box (the tail on the p drops below where the measurement is from). Is this vital to be pixel perfect?

**Comment by billposters** [comment]
Apologies @pauljervis - I'll add the correct spacings now and will upload in 10 mins. 

the 185 pix doesn't need to be pixel perfect, just nicely spaced and well balanced.

**Comment by billposters** [comment]
Quick questions @pauljervis - for text, should i measure down from one element to the top of the lower case or upper case?

**Comment by billposters** [comment]
Have ammended and added design spec above!

**Comment by pauljervis** [comment]
@billposters bottom of the tails and top of the upper case, please.

**Comment by billposters** [comment]
@pauljervis - ah I am sorry, do you need me to redo all the design specs?

**Comment by billposters** [comment]
@pauljervis - needs a little adjustment to line spacing that is all! 

Screen shot:

![IMG_9929](https://user-images.githubusercontent.com/48989022/58766479-17e50c00-8577-11e9-9ef7-bc75ec495925.JPG)

**Comment by pauljervis** [comment]
@billposters Do you not display the screens as full-screen? On Linux and Windows Chromium and Chrome go fullscreen by hitting F11 and it gets rid of the headers, etc. With that on my machine the spacings are the numbers provided.

**Comment by pauljervis** [comment]
@billposters looking at the specs again, the numbers won't be what was provided because I will have put a gap of say 100px but my 100px is from the bottom of the text (descender and all) to the top of the next text (ascender and all). 

Whereas the spaces on the spec are between the baseline of the first and midline of the second.

I don't really have a way of finding that out so if the space could be from the descender line to the ascender line, then I can very easily swap the margins out to the new values.

Thanks! (This may come up in a few other pages)

**Comment by billposters** [comment]
@pauljervis - yes sounds good to me. Either got with 100px or 80px (deducting descender and ascender height).

The design specs are quite exact so anything that gets close would be amazing.

**Comment by billposters** [comment]
![Influence_A_Follower_design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58787213-3e3f9180-85e1-11e9-965c-4cbe0dd006f8.jpg)
