### ISSUE TITLE
Create single component for email message

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#442]
Include avatar-component, ocean-profile and text below
Should accept user object as single prop
Don't worry about design, but
No scss

```

Dear [username],

    intro sentence / thank user for their data and for joining a congregation of billions.

    Your psychometric profile is attached to this email for future reference (or something).

    Spectre is always excited to welcome new followers who are: X, Y, Z (ocean text here)

    Share your psychological profile with your friends online? (pre-filled social post for facebook or twitter as a provocation) [SHARE POST?]

    If you feel unsure about making this private information public, you are right to be concerned. Click on the link below to reveal the secrets of the digital influence industry and find out more about why privacy matters... [CLICK] (link to spectre website to view their personal post experience page)
```

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/spectre-mail/pull/2

- Initial setup for the email template
- reconfigure the src folder so that we can spectre-mail can be merged into spectre in the future
- Add node-sass to automatically translate sass code to lib folder
- Comment out sass import lines in package.json/scripts (Not sure whether this is the best place to do this, please modify if you think it shoudn't)

![image](https://user-images.githubusercontent.com/3056154/73403566-aef89400-42bd-11ea-9f25-568ae2bafd22.png)

TODO:
- Purge useless CSS

Next:
I imagine that both [CLICK] and [SHARE POST] are mui buttons that the user can click. Are they?

**Comment by dhowe** [comment]
They are links of some kind, not sure if they need to be mui buttons (we will eventually have a design for this)

**Comment by dhowe** [comment]
Can we integrate the sass transpiling into babel, rather than as a command-line arg? Perhaps add something in the .babelrc pr package.json ?
