### ISSUE TITLE
TakeBackControl: same visual design as GDPR dialog

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#490]
Needs to have the same visual design as GDPR dialog on Login-page
The 'KEEP' option should be bigger and prominently highlighted

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/75292387-0ffa8580-57f2-11ea-959a-851597e53423.png)

https://github.com/dhowe/spectre/pull/519/commits/decc653eb47c400df2508cee9fa14c2cb3299323
Highlighted the "Keep" button and made a few CSS tweaks to match with the current Figma design.

Please notice that I made some global changes to the MUI button styles that make sense to me. Things like it's better to modify the global color theme rather than defining special button cases. I did a quick check on other pages to make sure that my change won't mess up other pages, happy to discuss and implement it in other ways if necessary.
